Pipeline:
  name: docker_template

GitRepo:
  name: sampleRepo
  gitProvider: NAGSDEMO
  path: nagarajuv-jfrog/jfrog-pipelines-samples-nagsdemo 
  branches:
    include: {{gitBranch}}

artifactoryIntegration: nagsdemoRT

Image:
  name: sampleImage
  sourceRepository: foo
  autoPull: false

DockerBuild:
  name: sampleBuild
  dockerImageName: pipelineslnp1.jfrogdev.org/ui/repos/tree/General/docker-local/jfrog/nagsartifact
  dockerFileName: Dockerfile
  dockerFileLocation: '.'
  dockerImageTag: ${run_number}

DockerPush:
  name: samplePush

BuildInfo:
  autoPublishBuildInfo: true
  name: sampleBuildInfo
